export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_USER = 'GET_USER';
export const SORT_BY_VALUE = 'SORT_BY_VALUE';
export const GET_NAME_PRODUCT = 'GET_NAME_PRODUCT';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_NAME_SEARCH = 'SET_NAME_SEARCH';
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
