export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_USER = "GET_USER";
export const SORT_BY_VALUE = "SORT_BY_VALUE";
export const GET_NAME_PRODUCT = "GET_NAME_PRODUCT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_NAME_SEARCH = "SET_NAME_SEARCH";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOADING_USER = "LOADING_USER";
export const UPDATE_GOOGLE_AUTH_ERROR_MESSAGE =
  "UPDATE_GOOGLE_AUTH_ERROR_MESSAGE";
export const LOGIN_ERROR_MESSAGE = "LOGIN_ERROR_MESSAGE";
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
